using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace TryGet.SourceGenerator
{
    /// <summary>
    /// V0.9.5 Iter 5：扫描 <c>[TryGet.EventHandler]</c> 标记静态方法，生成
    /// <c>__EventHandlerManifest_&lt;asm&gt;</c>，在 dual-trigger init 时把 handler 注册到
    /// <c>TryGet.EventHandlerRegistry</c>，<c>GameLauncher.CreateHost</c> 内部应用到 host.EventModule。
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class EventHandlerGenerator : IIncrementalGenerator
    {
        private const string AttributeMetadataName = "TryGet.EventHandlerAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var extractions = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeMetadataName,
                    predicate: static (node, _) => true,
                    transform: static (ctx, _) => ExtractHandler(ctx));

            var compilationAndExtractions = context.CompilationProvider
                .Combine(extractions.Collect());

            context.RegisterSourceOutput(compilationAndExtractions, static (spc, source) =>
            {
                var (compilation, exts) = source;

                // 先报告非法输入诊断（替代历史的静默 return null），再收集合法 handler 生成 manifest
                var handlers = ImmutableArray.CreateBuilder<EventHandlerInfo>();
                foreach (var ext in exts)
                {
                    if (ext.Diagnostic is { } diagnostic)
                        spc.ReportDiagnostic(diagnostic.ToDiagnostic());
                    if (ext.Info is { } info)
                        handlers.Add(info);
                }

                if (handlers.Count == 0) return;

                string assemblyName = compilation.AssemblyName ?? "Unknown";
                string safeAsmId = MakeSafeIdentifier(assemblyName);
                spc.AddSource($"__EventHandlerManifest_{safeAsmId}.g.cs", GenerateManifest(safeAsmId, handlers.ToImmutable(), assemblyName));
            });
        }

        private static EventHandlerExtraction ExtractHandler(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not IMethodSymbol method)
                return default; // attribute 限定标在方法上

            if (!method.IsStatic)
                return Fail(GeneratorDiagnostics.EventHandlerNotStatic, method, method.Name);

            if (method.Parameters.Length != 1 || method.ReturnType.SpecialType != SpecialType.System_Void)
                return Fail(GeneratorDiagnostics.EventHandlerInvalidSignature, method, method.Name);

            var eventType = method.Parameters[0].Type;
            if (eventType.TypeKind != TypeKind.Struct) // IEventModule 约束 T : struct
                return Fail(GeneratorDiagnostics.EventHandlerParamNotStruct, method,
                    eventType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));

            string containingTypeFullName = method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string eventTypeFullName = eventType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return new EventHandlerExtraction(new EventHandlerInfo(containingTypeFullName, method.Name, eventTypeFullName), null);
        }

        private static EventHandlerExtraction Fail(DiagnosticDescriptor descriptor, ISymbol locationSymbol, string messageArg)
            => new(null, new DiagnosticInfo(descriptor, DiagnosticInfo.GetSourceLocation(locationSymbol), messageArg));

        private static string GenerateManifest(string safeAsmId, ImmutableArray<EventHandlerInfo> handlers, string assemblyName)
        {
            var sb = new StringBuilder(1024);
            sb.AppendLine("// <auto-generated by TryGet.SourceGenerator (V0.9.5 EventHandlerGenerator) />");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("namespace TryGet.Generated");
            sb.AppendLine("{");
            sb.Append("    internal static class __EventHandlerManifest_").AppendLine(safeAsmId);
            sb.AppendLine("    {");
            sb.AppendLine("        private static bool _initialized;");
            sb.AppendLine();
            sb.AppendLine("#if UNITY_5_3_OR_NEWER");
            sb.AppendLine("        [global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");
            sb.AppendLine("        [global::UnityEngine.Scripting.Preserve]");
            sb.AppendLine("#endif");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("        public static void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_initialized && IsRegistered()) return;");
            sb.AppendLine("            _initialized = true;");
            sb.AppendLine();

            // C5：先注册所有 EventHandler 的结构化元数据（双轨 API 新路径）
            var sorted = handlers.Sort(static (a, b) =>
            {
                int c = string.CompareOrdinal(a.ContainingTypeFullName, b.ContainingTypeFullName);
                if (c != 0) return c;
                return string.CompareOrdinal(a.MethodName, b.MethodName);
            });

            foreach (var h in sorted)
            {
                string handlerSig = $"{h.ContainingTypeFullName}.{h.MethodName}";
                sb.Append("            global::TryGet.EventHandlerRegistry.RegisterWithMetadata(")
                  .Append('"').Append(handlerSig).Append("\", ")
                  .Append("typeof(").Append(h.EventTypeFullName).Append("), ")
                  .Append('"').Append(assemblyName).AppendLine("\");");
            }

            sb.AppendLine();
            // 再注册执行委托（向后兼容的旧路径）
            sb.AppendLine("            global::TryGet.EventHandlerRegistry.Register(bus =>");
            sb.AppendLine("            {");
            foreach (var h in sorted)
            {
                sb.Append("                bus.Subscribe<")
                  .Append(h.EventTypeFullName)
                  .Append(">(")
                  .Append(h.ContainingTypeFullName)
                  .Append('.')
                  .Append(h.MethodName)
                  .AppendLine(");");
            }

            sb.AppendLine("            });");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static bool IsRegistered()");
            sb.AppendLine("        {");
            sb.AppendLine("            var snapshot = global::TryGet.EventHandlerRegistry.Snapshot();");
            sb.AppendLine("            for (int i = 0; i < snapshot.Count; i++)");
            sb.AppendLine("            {");
            sb.Append("                if (snapshot[i].SourceAssembly == ").Append('"').Append(assemblyName).AppendLine("\")");
            sb.AppendLine("                    return true;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string MakeSafeIdentifier(string assemblyName)
        {
            var sb = new StringBuilder(assemblyName.Length);
            foreach (char c in assemblyName)
                sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
            return sb.ToString();
        }
    }

    internal readonly record struct EventHandlerInfo(
        string ContainingTypeFullName,
        string MethodName,
        string EventTypeFullName);

    /// <summary>
    /// transform 阶段的产出：合法 handler 的 <see cref="EventHandlerInfo"/>，或非法输入的 <see cref="DiagnosticInfo"/>。
    /// </summary>
    internal readonly record struct EventHandlerExtraction(EventHandlerInfo? Info, DiagnosticInfo? Diagnostic);
}
