using Microsoft.CodeAnalysis;

namespace TryGet.SourceGenerator
{
    /// <summary>
    /// 为生成的 manifest 提供 <c>ModuleInitializerAttribute</c> polyfill。
    ///
    /// Unity/老 target framework 可能没有内置 <c>System.Runtime.CompilerServices.ModuleInitializerAttribute</c>，
    /// 但 C# 编译器只需要编译单元里存在这个全名即可识别 module initializer。
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class ModuleInitializerSupportGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static spc =>
                spc.AddSource("__TryGetModuleInitializerAttribute.g.cs", @"
// <auto-generated by TryGet.SourceGenerator (ModuleInitializerSupportGenerator) />
#nullable disable
namespace System.Runtime.CompilerServices
{
#if !NET5_0_OR_GREATER
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
    internal sealed class ModuleInitializerAttribute : global::System.Attribute
    {
    }
#endif
}
"));
        }
    }
}
