using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TryGet.SourceGenerator
{
    /// <summary>
    /// V0.9.5 Iter 6：扫描 <c>IComponentSystem&lt;TComponent&gt;</c> 实现类，生成
    /// <c>__ComponentSystemManifest_&lt;asm&gt;</c>，在 dual-trigger init 时把 System 挂到
    /// <c>ComponentSystemHooks&lt;TComponent&gt;.AttachHook/DetachHook</c>。
    ///
    /// 与其他 Generator 不同：本 Generator 通过 Interface 实现而非 Attribute 触发
    /// （IComponentSystem 是契约接口，业务实现它而非额外标 attribute）。
    /// 使用 CreateSyntaxProvider 扫所有 class declaration，semantic 验证 interface 实现。
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class ComponentSystemGenerator : IIncrementalGenerator
    {
        private const string ComponentSystemInterfaceFullName = "TryGet.IComponentSystem`1";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var systemInfos = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) =>
                        node is ClassDeclarationSyntax cls
                        && cls.BaseList is not null
                        && !cls.Modifiers.Any(m => m.Text == "abstract")
                        && !cls.Modifiers.Any(m => m.Text == "static"),
                    transform: static (ctx, _) => ExtractInfo(ctx))
                .Where(static info => info is not null)
                .Select(static (info, _) => info!.Value);

            var compilationAndSystems = context.CompilationProvider.Combine(systemInfos.Collect());

            context.RegisterSourceOutput(compilationAndSystems, static (spc, source) =>
            {
                var (compilation, systems) = source;
                if (systems.IsDefaultOrEmpty) return;

                string safeAsmId = MakeSafeIdentifier(compilation.AssemblyName ?? "Unknown");
                spc.AddSource($"__ComponentSystemManifest_{safeAsmId}.g.cs",
                    GenerateManifest(safeAsmId, systems));
            });
        }

        private static ComponentSystemInfo? ExtractInfo(GeneratorSyntaxContext ctx)
        {
            var classNode = (ClassDeclarationSyntax)ctx.Node;
            if (ctx.SemanticModel.GetDeclaredSymbol(classNode) is not INamedTypeSymbol classSymbol)
                return null;

            if (classSymbol.IsAbstract || classSymbol.IsStatic) return null;

            // 扫所有实现接口，找 IComponentSystem<TComponent>
            foreach (var iface in classSymbol.AllInterfaces)
            {
                if (!iface.IsGenericType) continue;
                if (iface.OriginalDefinition.ToDisplayString() != "TryGet.IComponentSystem<TComponent>")
                    continue;

                if (iface.TypeArguments.Length != 1) continue;
                var componentType = iface.TypeArguments[0];

                string classFullName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                string componentFullName = componentType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                return new ComponentSystemInfo(classFullName, componentFullName);
            }

            return null;
        }

        private static string GenerateManifest(string safeAsmId, ImmutableArray<ComponentSystemInfo> systems)
        {
            var sb = new StringBuilder(1024);
            sb.AppendLine("// <auto-generated by TryGet.SourceGenerator (V0.9.5 ComponentSystemGenerator) />");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("namespace TryGet.Generated");
            sb.AppendLine("{");
            sb.Append("    internal static class __ComponentSystemManifest_").AppendLine(safeAsmId);
            sb.AppendLine("    {");
            sb.AppendLine("        private static bool _initialized;");
            sb.AppendLine();
            sb.AppendLine("#if UNITY_5_3_OR_NEWER");
            sb.AppendLine("        [global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");
            sb.AppendLine("        [global::UnityEngine.Scripting.Preserve]");
            sb.AppendLine("#endif");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("        public static void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_initialized) return;");
            sb.AppendLine("            _initialized = true;");

            var sorted = systems.Sort(static (a, b) => string.CompareOrdinal(a.ClassFullName, b.ClassFullName));
            int idx = 0;
            foreach (var s in sorted)
            {
                string varName = $"_sys{idx}";
                sb.Append("            var ").Append(varName).Append(" = new ").Append(s.ClassFullName).AppendLine("();");
                sb.Append("            global::TryGet.ComponentSystemHooks<")
                  .Append(s.ComponentFullName).Append(">.AttachHook += ").Append(varName).AppendLine(".OnAttach;");
                sb.Append("            global::TryGet.ComponentSystemHooks<")
                  .Append(s.ComponentFullName).Append(">.DetachHook += ").Append(varName).AppendLine(".OnDetach;");
                idx++;
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string MakeSafeIdentifier(string assemblyName)
        {
            var sb = new StringBuilder(assemblyName.Length);
            foreach (char c in assemblyName)
                sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
            return sb.ToString();
        }
    }

    internal readonly record struct ComponentSystemInfo(string ClassFullName, string ComponentFullName);
}
