using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace TryGet.SourceGenerator
{
    /// <summary>
    /// V0.9.5 Iter 5：扫描 <c>[TryGet.EventHandler]</c> 标记静态方法，生成
    /// <c>__EventHandlerManifest_&lt;asm&gt;</c>，在 dual-trigger init 时把 handler 注册到
    /// <c>TryGet.EventHandlerRegistry</c>，<c>Bootstrap.CreateHost</c> 内部应用到 host.EventBus。
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class EventHandlerGenerator : IIncrementalGenerator
    {
        private const string AttributeMetadataName = "TryGet.EventHandlerAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var handlerInfos = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeMetadataName,
                    predicate: static (node, _) => true,
                    transform: static (ctx, _) => ExtractHandlerInfo(ctx))
                .Where(static info => info is not null)
                .Select(static (info, _) => info!.Value);

            var compilationAndHandlers = context.CompilationProvider
                .Combine(handlerInfos.Collect());

            context.RegisterSourceOutput(compilationAndHandlers, static (spc, source) =>
            {
                var (compilation, handlers) = source;
                if (handlers.IsDefaultOrEmpty) return;

                string safeAsmId = MakeSafeIdentifier(compilation.AssemblyName ?? "Unknown");
                spc.AddSource($"__EventHandlerManifest_{safeAsmId}.g.cs", GenerateManifest(safeAsmId, handlers));
            });
        }

        private static EventHandlerInfo? ExtractHandlerInfo(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not IMethodSymbol method) return null;
            if (!method.IsStatic) return null;
            if (method.Parameters.Length != 1) return null;
            if (method.ReturnType.SpecialType != SpecialType.System_Void) return null;

            var eventType = method.Parameters[0].Type;
            if (eventType.TypeKind != TypeKind.Struct) return null; // IEventBus 约束 T : struct

            string containingTypeFullName = method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string methodName = method.Name;
            string eventTypeFullName = eventType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            return new EventHandlerInfo(containingTypeFullName, methodName, eventTypeFullName);
        }

        private static string GenerateManifest(string safeAsmId, ImmutableArray<EventHandlerInfo> handlers)
        {
            var sb = new StringBuilder(1024);
            sb.AppendLine("// <auto-generated by TryGet.SourceGenerator (V0.9.5 EventHandlerGenerator) />");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("namespace TryGet.Generated");
            sb.AppendLine("{");
            sb.Append("    internal static class __EventHandlerManifest_").AppendLine(safeAsmId);
            sb.AppendLine("    {");
            sb.AppendLine("        private static bool _initialized;");
            sb.AppendLine();
            sb.AppendLine("#if UNITY_5_3_OR_NEWER");
            sb.AppendLine("        [global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");
            sb.AppendLine("        [global::UnityEngine.Scripting.Preserve]");
            sb.AppendLine("#endif");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("        public static void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_initialized) return;");
            sb.AppendLine("            _initialized = true;");
            sb.AppendLine("            global::TryGet.EventHandlerRegistry.Register(bus =>");
            sb.AppendLine("            {");

            var sorted = handlers.Sort(static (a, b) =>
            {
                int c = string.CompareOrdinal(a.ContainingTypeFullName, b.ContainingTypeFullName);
                if (c != 0) return c;
                return string.CompareOrdinal(a.MethodName, b.MethodName);
            });

            foreach (var h in sorted)
            {
                sb.Append("                bus.Subscribe<")
                  .Append(h.EventTypeFullName)
                  .Append(">(")
                  .Append(h.ContainingTypeFullName)
                  .Append('.')
                  .Append(h.MethodName)
                  .AppendLine(");");
            }

            sb.AppendLine("            });");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string MakeSafeIdentifier(string assemblyName)
        {
            var sb = new StringBuilder(assemblyName.Length);
            foreach (char c in assemblyName)
                sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
            return sb.ToString();
        }
    }

    internal readonly record struct EventHandlerInfo(
        string ContainingTypeFullName,
        string MethodName,
        string EventTypeFullName);
}
