using Microsoft.CodeAnalysis;

namespace TryGet.SourceGenerator
{
    /// <summary>
    /// V0.9.5 Iter 1 烟测 Generator。
    ///
    /// 目的：验证 IIncrementalGenerator 管线在 dotnet build 与 Unity Editor 双端均能触发，
    /// 并能在 consumer 项目里看到生成文件。
    ///
    /// 后续 Iter 会替换为真正的 Module/System/EventHandler/ComponentSystem Generator。
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class HelloWorldGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 不依赖任何输入，直接在 PostInitialization 阶段生成一个标记文件。
            // 真实 Generator 会用 context.SyntaxProvider.ForAttributeWithMetadataName(...)
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource("__TryGetSourceGenerator_HelloWorld.g.cs",
                    "// <auto-generated by TryGet.SourceGenerator (V0.9.5 Iter 1 烟测) />\n" +
                    "// 若你能看到此文件，说明 IIncrementalGenerator 已经被宿主成功加载。\n" +
                    "namespace TryGet.Generated\n" +
                    "{\n" +
                    "    internal static class __TryGetSourceGeneratorHelloWorld\n" +
                    "    {\n" +
                    "        public const string Version = \"0.9.5-iter1\";\n" +
                    "    }\n" +
                    "}\n");
            });
        }
    }
}
