using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace TryGet.SourceGenerator
{
    /// <summary>
    /// V0.9.5 Iter 3：扫描 <c>[TryGet.Module(typeof(IFoo))]</c> 标记类，生成
    /// <c>__AssemblyManifest_&lt;asm&gt;</c> 内 dual-trigger init 方法，把 Module 注册到
    /// <c>TryGet.AssemblyManifestRegistry</c>。
    ///
    /// 设计要点：
    /// - <see cref="ForAttributeWithMetadataName"/> 入口，避免遍历整个语法树
    /// - <see cref="ModuleInfo"/> 是 value-equatable record（关键 incrementality 性能优化）
    /// - <c>[ModuleInitializer]</c>（C# 9.0+）+ <c>[RuntimeInitializeOnLoadMethod]</c>（Unity）
    ///   dual-trigger，<c>_initialized</c> flag 防重
    /// - <c>[UnityEngine.Scripting.Preserve]</c> 防 IL2CPP strip
    /// - 没有任何 [Module] 时不生成 Manifest 文件（noise-free）
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class ModuleManifestGenerator : IIncrementalGenerator
    {
        private const string ModuleAttributeMetadataName = "TryGet.ModuleAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 找到所有 [Module(typeof(IFoo))] 标记的类
            var moduleInfos = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    ModuleAttributeMetadataName,
                    predicate: static (node, _) => true,
                    transform: static (ctx, _) => ExtractModuleInfo(ctx))
                .Where(static info => info is not null)
                .Select(static (info, _) => info!.Value);

            // 收集 (CompilationName, ImmutableArray<ModuleInfo>) 用于聚合
            var compilationAndModules = context.CompilationProvider
                .Combine(moduleInfos.Collect());

            context.RegisterSourceOutput(compilationAndModules, static (spc, source) =>
            {
                var (compilation, modules) = source;
                if (modules.IsDefaultOrEmpty) return;

                string assemblyName = compilation.AssemblyName ?? "Unknown";
                string safeAsmId = MakeSafeIdentifier(assemblyName);

                string sourceText = GenerateManifest(safeAsmId, modules);
                spc.AddSource($"__AssemblyManifest_{safeAsmId}.g.cs", sourceText);
            });
        }

        private static ModuleInfo? ExtractModuleInfo(GeneratorAttributeSyntaxContext ctx)
        {
            // 取被标记的类符号
            if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol)
                return null;

            if (classSymbol.IsAbstract || classSymbol.IsStatic)
                return null;

            // 取 [Module(typeof(IFoo))] 的第一个构造器参数
            var attr = ctx.Attributes.FirstOrDefault();
            if (attr is null || attr.ConstructorArguments.Length == 0)
                return null;

            var serviceTypeArg = attr.ConstructorArguments[0];
            if (serviceTypeArg.Value is not INamedTypeSymbol serviceTypeSymbol)
                return null;

            // 类必须实现服务接口（编译期可由 Roslyn 自动检查；这里仅用 FullName 生成代码）
            string classFullName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string serviceFullName = serviceTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            return new ModuleInfo(classFullName, serviceFullName);
        }

        private static string GenerateManifest(string safeAsmId, ImmutableArray<ModuleInfo> modules)
        {
            var sb = new StringBuilder(1024);
            sb.AppendLine("// <auto-generated by TryGet.SourceGenerator (V0.9.5 ModuleManifestGenerator) />");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("namespace TryGet.Generated");
            sb.AppendLine("{");
            sb.Append("    internal static class __AssemblyManifest_").AppendLine(safeAsmId);
            sb.AppendLine("    {");
            sb.AppendLine("        private static bool _initialized;");
            sb.AppendLine();
            sb.AppendLine("#if UNITY_5_3_OR_NEWER");
            sb.AppendLine("        [global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");
            sb.AppendLine("        [global::UnityEngine.Scripting.Preserve]");
            sb.AppendLine("#endif");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("        public static void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_initialized) return;");
            sb.AppendLine("            _initialized = true;");
            sb.AppendLine("            global::TryGet.AssemblyManifestRegistry.Register(host =>");
            sb.AppendLine("            {");

            // 稳定排序，避免 Generator 输出在不同 Roslyn 版本下抖动
            var sorted = modules.Sort(static (a, b) => string.CompareOrdinal(a.ClassFullName, b.ClassFullName));
            foreach (var m in sorted)
            {
                sb.Append("                host.Register<")
                  .Append(m.ServiceFullName)
                  .Append(">(new ")
                  .Append(m.ClassFullName)
                  .AppendLine("());");
            }

            sb.AppendLine("            });");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string MakeSafeIdentifier(string assemblyName)
        {
            var sb = new StringBuilder(assemblyName.Length);
            foreach (char c in assemblyName)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }
            return sb.ToString();
        }
    }

    /// <summary>
    /// Value-equatable record（关键 incrementality 性能优化）。
    /// 仅含 string 字段，不持 ISymbol / SyntaxNode 引用，避免 Compilation 锁定。
    /// </summary>
    internal readonly record struct ModuleInfo(string ClassFullName, string ServiceFullName);
}

namespace System.Runtime.CompilerServices
{
    // netstandard2.0 polyfill for C# 9+ records / init accessors
    internal static class IsExternalInit { }
}
