using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace TryGet.SourceGenerator
{
    /// <summary>
    /// V0.9.5 Iter 4：扫描 <c>[TryGet.SystemRegister(Phase, groupName)]</c> 标记类，生成
    /// <c>__SystemManifest_&lt;asm&gt;</c> 内 dual-trigger init 方法，把 System 注册到
    /// <c>TryGet.SystemRegistry</c>（业务后续在 EntityWorld 构造后调 <c>SystemRegistry.ApplyAll</c>）。
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class SystemRegisterGenerator : IIncrementalGenerator
    {
        private const string AttributeMetadataName = "TryGet.SystemRegisterAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var systemInfos = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeMetadataName,
                    predicate: static (node, _) => true,
                    transform: static (ctx, _) => ExtractSystemInfo(ctx))
                .Where(static info => info is not null)
                .Select(static (info, _) => info!.Value);

            var compilationAndSystems = context.CompilationProvider
                .Combine(systemInfos.Collect());

            context.RegisterSourceOutput(compilationAndSystems, static (spc, source) =>
            {
                var (compilation, systems) = source;
                if (systems.IsDefaultOrEmpty) return;

                string assemblyName = compilation.AssemblyName ?? "Unknown";
                string safeAsmId = MakeSafeIdentifier(assemblyName);

                spc.AddSource($"__SystemManifest_{safeAsmId}.g.cs", GenerateManifest(safeAsmId, systems));
            });
        }

        private static SystemInfo? ExtractSystemInfo(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol) return null;
            if (classSymbol.IsAbstract || classSymbol.IsStatic) return null;

            var attr = ctx.Attributes.FirstOrDefault();
            if (attr is null || attr.ConstructorArguments.Length == 0) return null;

            // 第一个参数：Phase enum 值
            var phaseArg = attr.ConstructorArguments[0];
            if (phaseArg.Kind != TypedConstantKind.Enum || phaseArg.Value is not int phaseValue)
                return null;

            // 第二个参数：groupName（可选 string）
            string? groupName = null;
            if (attr.ConstructorArguments.Length >= 2)
            {
                var nameArg = attr.ConstructorArguments[1];
                groupName = nameArg.Value as string;
            }

            string classFullName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return new SystemInfo(classFullName, phaseValue, groupName);
        }

        private static string GenerateManifest(string safeAsmId, ImmutableArray<SystemInfo> systems)
        {
            var sb = new StringBuilder(1024);
            sb.AppendLine("// <auto-generated by TryGet.SourceGenerator (V0.9.5 SystemRegisterGenerator) />");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("namespace TryGet.Generated");
            sb.AppendLine("{");
            sb.Append("    internal static class __SystemManifest_").AppendLine(safeAsmId);
            sb.AppendLine("    {");
            sb.AppendLine("        private static bool _initialized;");
            sb.AppendLine();
            sb.AppendLine("#if UNITY_5_3_OR_NEWER");
            sb.AppendLine("        [global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");
            sb.AppendLine("        [global::UnityEngine.Scripting.Preserve]");
            sb.AppendLine("#endif");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("        public static void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_initialized) return;");
            sb.AppendLine("            _initialized = true;");
            sb.AppendLine("            global::TryGet.SystemRegistry.Register(world =>");
            sb.AppendLine("            {");

            var sorted = systems.Sort(static (a, b) => string.CompareOrdinal(a.ClassFullName, b.ClassFullName));
            foreach (var s in sorted)
            {
                string phaseLiteral = s.PhaseValue switch
                {
                    0 => "global::TryGet.Phase.Enter",
                    1 => "global::TryGet.Phase.Update",
                    2 => "global::TryGet.Phase.Exit",
                    _ => $"(global::TryGet.Phase){s.PhaseValue}",
                };

                if (s.GroupName is null)
                {
                    sb.Append("                world.RegisterSystem(new ")
                      .Append(s.ClassFullName)
                      .Append("(), ")
                      .Append(phaseLiteral)
                      .AppendLine(");");
                }
                else
                {
                    // 按 (Phase, GroupName) cache group 是 V0.9.5+ 优化空间；当前生成代码每次 new 一个 group
                    // 实际多 System 同 group 同 phase 的情况，业务可手动注册并复用 group
                    sb.Append("                world.RegisterSystem(new ")
                      .Append(s.ClassFullName)
                      .Append("(), ")
                      .Append(phaseLiteral)
                      .Append(", new global::TryGet.SystemGroup(\"")
                      .Append(EscapeString(s.GroupName))
                      .AppendLine("\"));");
                }
            }

            sb.AppendLine("            });");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string MakeSafeIdentifier(string assemblyName)
        {
            var sb = new StringBuilder(assemblyName.Length);
            foreach (char c in assemblyName)
                sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
            return sb.ToString();
        }

        private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    internal readonly record struct SystemInfo(string ClassFullName, int PhaseValue, string? GroupName);
}
